defaults:
  - real_single_arm

agent:
  agent_name: teleop
  max_lin_vel: 10
  max_rot_vel: 10
  max_gripper_vel: 1
  spatial_coeff: 1
  pos_action_gain: 1.0
  rot_action_gain: 1.0
  gripper_action_gain: 1
  rmat_reorder: [-2, -1, -3, 4]
  right_controller: true

model:
  obs_horizon: 1
  ac_horizon: 1
  pred_horizon: 1
